main: main.rpg_main
version: 0.1
name: RPG
author: B1GB0Y

commands:
     createnewcharacter:
          description: Erstelle einen neuen Character
     loadcharacter:
          description: Lädt einen Character
     logoutcharacter:
         description: Logout aus Character
     deletecharacter:
         description: Löscht Character
     listcharacter:
         description: Listet Character auf
     money:
         description: Zeigt das Geld deines Characters an
     saveinv:
          description: Speichert Inv
     loadinv:
          description: Ladet Inv
     rpg commands:
          description: Zeigt alle Befehle an
     rpg version:
          description: Zeigt Plugin Version an
     minigame:
          description: Erzeugt ein Minigame
     dungeon:
          description: Erzeugt einen dungeon
     createQuest:
          description: Erzeugt eine Quest
     addDescription:
          description: Fügt einer Quest eine Beschreibung zu
     printQuest:
          description: Zeigt alle Informationen einer Quest an
     addMissionTarget:
          description: Fügt einer Quest ein Zwischenziel zu
     editMissionTarget:
          description: Editiert ein Zwischenziel
     deleteMissionTarget:
          description: Löscht ein Zwischenziel
     spawnQuestNPC:
          description: Spawnt einen NPC der für Quests genutzt werden kann
     bindQuest:
          description: Bindet eine Quest an ein Objekt